name: Gateway API Contract Tests Status

on:
  repository_dispatch:
    types: [ contract_tests_status ]

jobs:
  build:
    name: Contract Tests Status
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: |
           if [[ ${{ github.event.client_payload.workflow_status }} != 'success' ]]; then
              echo "The contract tests are failing..."
              exit 1
           else
              exit 0
           fi
