name: Gateway API Contract Tests

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Contract Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  dispatch-contract-tests-event:
    runs-on: ubuntu-latest
    steps:
      - name: get ephemeral deployment url
        run: |
          echo "GATEWAY_URL=${{ secrets.GATEWAY_URL }}" >> $GITHUB_ENV
          echo "EVENT_TYPE=contract_tests" >> $GITHUB_ENV

      - name: Trigger contract tests job
        run: |
          curl --silent --show-error --fail --location --request POST 'https://github-worker.radixdlt.com/repos/radixdlt/radixdlt-python-clients/dispatches' \
            --header 'Accept: application/vnd.github.v3+json' \
            --header 'Authorization: Basic ${{secrets.CF_GITHUB_WORKER_ENCODED_BASIC_AUTH}}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "event_type": "${{env.EVENT_TYPE}}",
                "client_payload": {
                    "gateway_url": "${{env.GATEWAY_URL}}"
                }
            }'
